from .api import BackupManager, IPhoneBackup, WABackup
from .errors import (
    BackupError,
    DatabaseConnectionError,
    DatabaseErrorWA,
    DirectoryAccessError,
    DomainError,
    FileCopyError,
    InvalidBackupError,
    MediaNotFoundError,
    OwnerProfileNotFoundError,
    RecordNotFoundError,
    UnexpectedDomainError,
    UnsupportedSchemaError,
)
from .files import FilenameAndHash
from .models import (
    BackupDiscoveryInfo,
    BackupDiscoveryStatus,
    BackupFetchResult,
    ChatDumpPayload,
    ChatInfo,
    ChatType,
    ContactInfo,
    MessageAuthor,
    MessageAuthorKind,
    MessageAuthorSource,
    MessageInfo,
    Reaction,
    WABackupDelegate,
)
from .utils import canonical_json_dumps

__version__ = "0.1.1"

__all__ = [
    "BackupError",
    "BackupDiscoveryInfo",
    "BackupDiscoveryStatus",
    "BackupFetchResult",
    "BackupManager",
    "ChatDumpPayload",
    "ChatInfo",
    "ChatType",
    "ContactInfo",
    "DatabaseConnectionError",
    "DatabaseErrorWA",
    "DirectoryAccessError",
    "DomainError",
    "FileCopyError",
    "FilenameAndHash",
    "IPhoneBackup",
    "InvalidBackupError",
    "MediaNotFoundError",
    "MessageAuthor",
    "MessageAuthorKind",
    "MessageAuthorSource",
    "MessageInfo",
    "OwnerProfileNotFoundError",
    "Reaction",
    "RecordNotFoundError",
    "UnexpectedDomainError",
    "UnsupportedSchemaError",
    "WABackup",
    "WABackupDelegate",
    "__version__",
    "canonical_json_dumps",
]
